export const jsonMetadata = [
  {
    type: "CustomObject",
    fullName: "Product_Catalog__c",
    label: "Product Catalog",
    pluralLabel: "Product Catalogs",
    description: "Catalog of products available for sale",
    deploymentStatus: "Deployed",
    allowInChatterGroups: true,
    nameField: {
      label: "Product Name",
      type: "Text",
      trackHistory: false,
    },
    enableActivities: true,
    enableBulkApi: true,
    enableFeeds: false,
    enableHistory: true,
    enableLicensing: false,
    enableReports: true,
    enableSearch: true,
    enableSharing: true,
    sharingModel: "ReadWrite",
    externalSharingModel: "ReadWrite",
    enableStreamingApi: true,
    visibility: "Public",
    fields: [
      {
        type: "AutoNumber",
        label: "Product SKU",
        fullName: "Product_SKU__c",
        displayFormat: "SKU-{0000}",
        description: "System-generated product SKU for tracking",
        inlineHelpText: "Unique product identifier. Example: SKU-0001",
        startingNumber: 1000,
      },
      {
        type: "Checkbox",
        label: "Is Active",
        fullName: "Is_Active__c",
        defaultValue: true,
        description: "Indicates if the product is currently active",
        inlineHelpText: "Check this box if the product is available for sale",
        trackHistory: false,
        required: false,
        externalId: false,
      },
      {
        type: "Currency",
        fullName: "Unit_Price__c",
        label: "Unit Price",
        defaultValue: 0,
        description: "Price per unit of the product",
        inlineHelpText: "Enter the unit price in USD",
        precision: 18,
        scale: 2,
        required: true,
      },
      {
        fullName: "Launch_Date__c",
        label: "Launch Date",
        type: "Date",
        defaultValue: "DATE(2026,1,19)",
        description: "Date when the product was launched",
        inlineHelpText: "Select the product launch date",
        required: false,
      },
      {
        fullName: "Last_Updated__c",
        label: "Last Updated",
        type: "DateTime",
        defaultValue: "NOW()",
        description: "Date and time of last update",
        inlineHelpText: "Automatically set to current date/time",
        required: false,
      },
      {
        fullName: "Supplier_Email__c",
        label: "Supplier Email",
        type: "Email",
        description: "Primary email address of the supplier",
        inlineHelpText: "Enter a valid email address",
        required: false,
        caseSensitive: false,
        unique: false,
        externalId: false,
      },
      {
        fullName: "Warehouse_Location__c",
        label: "Warehouse Location",
        type: "Location",
        description: "Geographic coordinates of the warehouse",
        inlineHelpText: "Enter latitude and longitude",
        required: false,
        displayLocationInDecimal: true,
        scale: 5,
      },
      {
        fullName: "Stock_Quantity__c",
        label: "Stock Quantity",
        type: "Number",
        precision: 10,
        scale: 0,
        required: true,
        unique: false,
        isAIPredictionField: false,
        description: "Current quantity in stock",
        inlineHelpText: "Enter the number of units available",
      },
      {
        fullName: "Discount_Rate__c",
        label: "Discount Rate",
        type: "Percent",
        precision: 5,
        scale: 2,
        required: false,
        description: "Discount percentage applied to unit price",
        inlineHelpText: "Enter discount as a percentage",
      },
      {
        fullName: "Supplier_Phone__c",
        label: "Supplier Phone",
        type: "Phone",
        required: false,
        description: "Phone number of the supplier",
        inlineHelpText: "+1 (555) 123-4567",
      },
      {
        fullName: "Product_Category__c",
        label: "Product Category",
        type: "Picklist",
        required: true,
        description: "Primary category of the product",
        inlineHelpText: "Select the appropriate product category",
        valueSet: {
          restricted: true,
          values: [
            {
              fullName: "Electronics",
              label: "Electronics",
              default: true,
            },
            {
              fullName: "Clothing",
              label: "Clothing",
              default: false,
            },
            {
              fullName: "Home_Goods",
              label: "Home Goods",
              default: false,
            },
            {
              fullName: "Sports",
              label: "Sports & Outdoors",
              default: false,
            },
          ],
        },
      },
      {
        fullName: "Product_Tags__c",
        label: "Product Tags",
        type: "MultiselectPicklist",
        required: false,
        description: "Multiple tags for product categorization",
        inlineHelpText: "Select one or more applicable tags",
        valueSet: {
          restricted: true,
          sorted: false,
          values: [
            {
              fullName: "New_Arrival",
              label: "New Arrival",
              default: false,
            },
            {
              fullName: "Best_Seller",
              label: "Best Seller",
              default: false,
            },
            {
              fullName: "On_Sale",
              label: "On Sale",
              default: false,
            },
            {
              fullName: "Limited_Edition",
              label: "Limited Edition",
              default: false,
            },
          ],
        },
        trackHistory: false,
        visibleLines: 4,
      },
      {
        fullName: "Product_Code__c",
        label: "Product Code",
        type: "Text",
        length: 50,
        required: false,
        unique: false,
        description: "Unique external product code",
        inlineHelpText: "Enter the manufacturer's product code",
        externalId: true,
        trackHistory: false,
        trackTrending: false,
      },
      {
        fullName: "Short_Description__c",
        label: "Short Description",
        type: "TextArea",
        required: false,
        description: "Brief product description",
        inlineHelpText: "Enter a short product summary",
        trackHistory: false,
        trackTrending: false,
      },
      {
        fullName: "Encrypted_Serial_Number__c",
        label: "Encrypted Serial Number",
        type: "EncryptedText",
        required: false,
        length: 175,
        maskChar: "asterisk",
        maskType: "ssn",
        description: "Encrypted product serial number",
        inlineHelpText: "Secure serial number storage",
        trackHistory: false,
        trackTrending: false,
      },
      {
        fullName: "Full_Description__c",
        label: "Full Description",
        type: "LongTextArea",
        length: 32768,
        visibleLines: 5,
        description: "Detailed product description",
        inlineHelpText: "Enter comprehensive product details",
        trackHistory: false,
        trackTrending: false,
      },
      {
        fullName: "Marketing_Content__c",
        label: "Marketing Content",
        type: "Html",
        length: 32768,
        visibleLines: 25,
        description: "Rich text marketing content",
        inlineHelpText: "Enter formatted marketing copy",
        trackHistory: false,
        trackTrending: false,
      },
      {
        fullName: "Preferred_Delivery_Time__c",
        label: "Preferred Delivery Time",
        type: "Time",
        required: false,
        description: "Preferred time for delivery",
        inlineHelpText: "Select delivery time window",
        trackHistory: false,
        trackTrending: false,
      },
      {
        fullName: "Product_Website__c",
        label: "Product Website",
        type: "Url",
        required: false,
        description: "Product information website",
        inlineHelpText: "Enter URL starting with http:// or https://",
        trackHistory: false,
        trackTrending: false,
      },
      {
        fullName: "Account_Lookup__c",
        label: "Account",
        type: "Lookup",
        referenceTo: "Another_Productt_Catalog__c",
        relationshipName: "Account",
        relationshipLabel: "Accounts",
        deleteConstraint: "Restrict", // required=true only allowed with Restrict
        description: "Lookup to Account object",
        inlineHelpText: "Select the related Account record",
        required: true,
      },
      // {
      //   "type": "Formula",
      //   "label": "Discounted Price",
      //   "fullName": "Discounted_Price__c",
      //   "returnType": "Currency",
      //   "formula": "$20.00",
      //   "blankOption": "BlankAsZero",
      //   "description": "Calculated price after applying discount",
      //   "inlineHelpText": "Automatically calculated: Unit Price minus Discount Rate",
      //   "externalId": false,
      //   "required": false,
      //   "unique": false,
      //   "trackHistory": false
      // }
    ],
  },
  {
    type: "CustomObject",
    fullName: "Another_Product_Catalog__c",
    label: "Product Catalog",
    pluralLabel: "Product Catalogs",
    description: "Catalog of products available for sale",
    deploymentStatus: "Deployed",
    allowInChatterGroups: true,
    nameField: {
      label: "Product Name",
      type: "Text",
      trackHistory: false,
    },
    enableActivities: true,
    enableBulkApi: true,
    enableFeeds: false,
    enableHistory: true,
    enableLicensing: false,
    enableReports: true,
    enableSearch: true,
    enableSharing: true,
    sharingModel: "ReadWrite",
    externalSharingModel: "ReadWrite",
    enableStreamingApi: true,
    visibility: "Public",
    fields: [
      {
        type: "AutoNumber",
        label: "Product SKU",
        fullName: "Product_SKU__c",
        displayFormat: "SKU-{0000}",
        description: "System-generated product SKU for tracking",
        inlineHelpText: "Unique product identifier. Example: SKU-0001",
        startingNumber: 1000,
      },
      {
        type: "Checkbox",
        label: "Is Active",
        fullName: "Is_Active__c",
        defaultValue: true,
        description: "Indicates if the product is currently active",
        inlineHelpText: "Check this box if the product is available for sale",
        trackHistory: false,
        required: false,
        externalId: false,
      },
    ],
  },
] as const;
