import { SalesforceMetadataTranspiler } from "./salesforceMetadataTranspiler";

const transpilerConfig = {
  apiVersion: "v65.0", // Required Salesforce API version
  outputDirectory: "./output", // Optional, default './output'
  validateOnly: true, // Optional, default false
};

const transpiler = new SalesforceMetadataTranspiler(transpilerConfig);

const schema = {
  type: "CustomObject",
  metaData: [
    {
      label: "Asset",
      pluralLabel: "Assets",
      description:
        "Represents a company asset used for tracking inventory and lifecycle status.",
      deploymentStatus: "Deployed",
      allowInChatterGroups: true,
      nameField: {
        label: "Asset Name",
        type: "Text",
        trackHistory: false,
      },
      enableActivities: true,
      enableBulkApi: true,
      enableFeeds: false,
      enableHistory: true,
      enableLicensing: false,
      enableReports: true,
      enableSearch: true,
      enableSharing: true,
      enableStreamingApi: true,
      visibility: "Public",
      fields: [
        {
          type: "AutoNumber",
          label: "Asset ID",
          fullName: "Asset_ID__c",
          displayFormat: "ASSET-{YYYY}-{0000}",
          description:
            "Automatically generated identifier for each asset record, including year of creation.",
          helpText:
            "This field is auto-generated by Salesforce. Example: ASSET-2026-0001",
          startingNumber: 1,
        },
        {
          type: "Formula",
          label: "Asset Status Label",
          fullName: "Asset_Status_Label__c",
          returnType: "Text",
          formula:
            'IF(NOT(ISBLANK(Asset_ID__c)), "ACTIVE: " & Name, "INACTIVE")',
          blankOption: "BlankAsZero",
          description:
            "Displays a human-readable status based on whether the asset has been assigned an ID.",
          helpText: "Shows ACTIVE or INACTIVE followed by the record name.",
          externalId: false,
          required: false,
          unique: false,
          trackHistory: false,
        },
      ],
    },
    {
      label: "Device",
      pluralLabel: "Devices",
      description:
        "Represents hardware devices assigned to employees or departments.",
      deploymentStatus: "Deployed",
      allowInChatterGroups: true,
      nameField: {
        label: "Device Name",
        type: "Text",
        trackHistory: false,
      },
      enableActivities: true,
      enableBulkApi: true,
      enableFeeds: false,
      enableHistory: true,
      enableLicensing: false,
      enableReports: true,
      enableSearch: true,
      enableSharing: true,
      enableStreamingApi: true,
      visibility: "Public",
      fields: [
        {
          type: "AutoNumber",
          label: "Device Serial Number",
          fullName: "Device_Serial__c",
          displayFormat: "DEV-{000000}",
          description: "System-generated serial number for internal tracking.",
          helpText: "Internal serial number. Example: DEV-000123",
          startingNumber: 1,
        },
        {
          type: "Formula",
          label: "Device Warranty Check",
          fullName: "Warranty_Check__c",
          returnType: "Text",
          formula:
            'IF(CONTAINS(Name, "Refurbished"), "Limited Warranty", "Full Warranty")',
          blankOption: "BlankAsBlank",
          description: "Determines warranty status based on the device name.",
          helpText:
            "Automatically flags warranty type based on whether the name contains 'Refurbished'.",
          externalId: false,
          required: false,
          unique: false,
          trackHistory: false,
        },
      ],
    },
  ],
} as const;

async function transpileSchema() {
  const result = await transpiler.transpile(schema);

  console.log(result);
}

transpileSchema();
